name: commentsearch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - fastapi=0.63.0
  - more-itertools=8.7.0
  - numpy=1.20.1
  - pip=21.0.1
  - protobuf=3.14.0
  - psycopg2=2.8.6
  - pymongo=3.11.0
  - python=3.9.1
  - pytorch=1.7.1
  - requests=2.25.1
  - scikit-learn=0.24.1
  - sentencepiece==0.1.95
  - sentence-transformers=0.4.1
  - tqdm=4.56.2
  - transformers=4.3.2
  - uvicorn=0.13.3
  - cxx-compiler
  - pip:
      - hnswlib==0.5.1
